const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}
async function checkAdmin(){if(!tg?.initData)return;try{const r=await fetch("/api/admin/check",{headers:{"X-Telegram-Init-Data":tg.initData}});if(r.ok)document.getElementById("adminBar")?.classList.remove("hide")}catch(e){}}
function openAdmin(){if(tg?.HapticFeedback)tg.HapticFeedback.impactOccurred("light");location.href="/admin.html"}
let products=[];let cartData=JSON.parse(localStorage.getItem("bcrve85_cart")||"[]");const euro=n=>Number(n).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});const save=()=>{localStorage.setItem("bcrve85_cart",JSON.stringify(cartData));update()};function update(){const el=document.getElementById("count");if(el)el.textContent=cartData.reduce((a,x)=>a+x.qty,0)}
async function loadProducts(){try{const r=await fetch("/api/products");if(!r.ok)throw new Error();products=await r.json();render();update()}catch(e){document.getElementById("products").innerHTML='<div class="empty">Catalogue indisponible pour le moment.</div>'}}
function render(cat="all"){document.getElementById("chips").innerHTML=[["all","Tout"],["selection","Sélection"],["edition","Édition"],["packs","Packs"]].map(x=>`<button class="chip ${x[0]===cat?"on":""}" onclick="render('${x[0]}')">${x[1]}</button>`).join("");const list=cat==="all"?products:products.filter(p=>p.cat===cat);document.getElementById("products").innerHTML=list.map(p=>`<article class="card"><div class="visual"><span>JUL · 13</span></div><div class="info"><div class="name">${escapeHtml(p.name)}</div><div class="sub">${escapeHtml(p.sub||"")}</div><div class="row"><span class="price">${euro(p.price)}</span><button class="add" onclick="add(${p.id})">+</button></div></div></article>`).join("")}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}function add(id){let x=cartData.find(x=>x.id===id);x?x.qty++:cartData.push({id,qty:1});save();toast("Ajouté · c’est carré 😎")}
function cart(){let lines=cartData.map(x=>{let p=products.find(p=>p.id===x.id);if(!p)return "";return `<div class="line"><div><b>${escapeHtml(p.name)}</b><div class="sub">Quantité : ${x.qty}</div></div><div>${euro(p.price*x.qty)}<br><button onclick="removeItem(${p.id})">−</button></div></div>`}).join("");let total=cartData.reduce((a,x)=>{let p=products.find(p=>p.id===x.id);return a+(p?p.price*x.qty:0)},0);show(`<button class="close" onclick="closeModal()">×</button><h3>Votre panier</h3>${lines||'<div class="empty">Votre panier est vide.</div>'}${cartData.length?`<div class="line"><b>Total</b><b>${euro(total)}</b></div><div class="notice">Paiement : <b>espèces</b> lors de la remise.</div><button class="full" onclick="order()">Confirmer la commande</button>`:""}`)}
function removeItem(id){let x=cartData.find(x=>x.id===id);if(!x)return;x.qty--;if(x.qty<=0)cartData=cartData.filter(x=>x.id!==id);save();cart()}
async function order(){if(!tg?.initData){show(`<h3>Ouvrez la boutique dans Telegram</h3><p>La commande doit être validée depuis Telegram.</p>`);return}const items=cartData.map(x=>({id:x.id,qty:x.qty}));const btn=document.querySelector(".full");if(btn){btn.disabled=true;btn.textContent="Envoi…"}try{const r=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json","X-Telegram-Init-Data":tg.initData},body:JSON.stringify({items})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Erreur");cartData=[];save();show(`<h3>Commande enregistrée</h3><p>Votre commande <b>#${data.order_id}</b> a bien été transmise à BCRVE85.</p><div class="notice"><b>Paiement :</b> espèces<br><b>Total :</b> ${euro(data.total)}<br><b>Statut :</b> à préparer</div><button class="full" onclick="closeModal()">Fermer</button>`)}catch(e){if(btn){btn.disabled=false;btn.textContent="Confirmer la commande"}toast(e.message||"Erreur")}}
function profile(){show(`<button class="close" onclick="closeModal()">×</button><h3>Votre espace</h3><div class="line"><span>Compte Telegram</span><span>Connecté</span></div><div class="line"><span>Paiement</span><span>Espèces</span></div>`)}
function favorites(){show(`<button class="close" onclick="closeModal()">×</button><h3>Favoris</h3><div class="empty">Les favoris arrivent bientôt.</div>`)}
function show(html){
  const modal=document.getElementById("modal");
  const sheet=document.getElementById("sheet");
  sheet.innerHTML=html;
  modal.classList.remove("hide");
  Object.assign(modal.style,{position:"fixed",left:"0",top:"0",right:"0",bottom:"0",width:"100vw",height:"100dvh",zIndex:"10000",display:"block",padding:"0",margin:"0",background:"rgba(0,0,0,.42)",overflow:"hidden"});
  Object.assign(sheet.style,{position:"fixed",left:"50%",top:"50%",transform:"translate(-50%,-50%)",boxSizing:"border-box",display:"block",width:"min(430px,calc(100vw - 32px))",maxWidth:"calc(100vw - 32px)",maxHeight:"calc(100dvh - 120px)",margin:"0",padding:"20px 18px 22px",background:"#fffdfa",color:"#181817",borderRadius:"24px",overflow:"auto",boxShadow:"0 20px 60px rgba(0,0,0,.22)",zIndex:"10001"});
  sheet.scrollTop=0;
}
function closeModal(){const modal=document.getElementById("modal");modal.classList.add("hide");modal.style.display="none"}
function home(btn){window.scrollTo({top:0,behavior:"smooth"});nav(btn)}function shop(btn){document.getElementById("shop").scrollIntoView({behavior:"smooth"});nav(btn)}function nav(btn){document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active")}function toast(t){let d=document.createElement("div");d.textContent=t;Object.assign(d.style,{position:"fixed",bottom:"95px",left:"50%",transform:"translateX(-50%)",background:"#181817",color:"#fff",padding:"11px 16px",borderRadius:"99px",zIndex:99,fontSize:"12px"});document.body.appendChild(d);setTimeout(()=>d.remove(),1600)}loadProducts();checkAdmin();
