name = "bcrve"
main = "worker.js"
compatibility_date = "2026-09-30"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bcrve-db"
database_id = "9f66b24e-3861-40be-a8a6-bcd3b10f9d75"
